site_name: ICEYE Product Documentation
site_description: Documentation related to ICEYE Products

# Repository
repo_name: iceye-ltd/product-documentation
repo_url: https://github.com/iceye-ltd/product-documentation
edit_uri: edit/main/docs/
site_url: https://iceye-ltd.github.io/product-documentation/

nav:
    - Welcome to ICEYE: index.md
    - The ICEYE Fleet: productguide/fleet.md
    - ICEYE Products: productguide/products.md
    - Data Formats: productguide/dataformats.md
    - Ordering data: productguide/ordering.md
    - Support: productguide/support.md
    - An Overview of SAR Imaging : 
        - The Value Of SAR Imaging : productguide/OverviewOfSAR/overviewOfSAR.md
        - A Simple Form Of RADAR Imaging : productguide/OverviewOfSAR/simpleFormOfImaging.md
        - The Remarkable Story Of SAR : productguide/OverviewOfSAR/remarkableStory.md
        - Range Resolution : productguide/OverviewOfSAR/rangeResolution.md
        - The Beautiful Equations : productguide/OverviewOfSAR/beautifulEquations.md
        - SAR Processing Overview : productguide/OverviewOfSAR/sarProcessing.md
        - Separating Signals From Noise : productguide/OverviewOfSAR/noise.md
        - The Innovation : productguide/OverviewOfSAR/theInnovation.md
    - Collection Characteristics : productguide/collectioncharacteristics.md
    - About: about.md
theme:
    name: material
    palette:
        primary: black
        accent: green
    logo: assets/svg-iceye-icon-white.svg
    favicon: assets/favicon.ico
    custom_dir: overrides

plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
   
extra:
  version:
    provider: mike


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js