site_name: ICEYE Product Documentation
site_description: Documentation related to ICEYE Products

# Repository
repo_name: ""
repo_url: ""
edit_uri: ""
site_url: https://iceye-ltd.github.io/product-documentation

nav:
    - Welcome: index.md
    - Data Product Specification:
       - 1. Introduction : productspecification/introduction.md
       - 2. Imaging Modes : productspecification/imagingmodes.md
       - 3. Tasking : productspecification/tasking.md
       - 4. Catalog : productspecification/catalog.md
       - 5. Data Products : productspecification/dataproducts.md
       - Glossary : productspecification/glossary.md
       - Disclaimer : productspecification/disclaimer.md
#   - The ICEYE Fleet: productguide/fleet.md
#   - ICEYE SAR Imagery: 
#       - Types of SAR Collection : productguide/typesofsarcollection.md
#       - Types of SAR Data Products : productguide/sardataproducts.md
#   - Ordering SAR imagery :
#       - Ordering data: productguide/ordering.md
#       - Support: productguide/support.md
#   - Data Format Specification : 
#       - SAR Data Formatting Options : productFormats/introduction.md
#       - Packaging : productFormats/packaging.md
#       - Image Products :
#           - Single Look Complex Image : productFormats/slc.md 
#          - Amplitude Image : productFormats/grd.md
#      - Additional Products :
#            - Colorized Sub-aperture Image : productFormats/csi.md
#            - SAR Video : productFormats/vid.md
#        - Upcoming Formats : productFormats/upcomingformats.md
    - Metadata Reference: productFormats/metadata.md
    - SAR 101 : 
      - What is SAR ? : 
          - The Value Of SAR Imaging : foundations/OverviewOfSAR/overviewOfSAR.md
          - A Simple Form Of RADAR Imaging : foundations/OverviewOfSAR/simpleFormOfImaging.md
          - The Remarkable Story Of SAR : foundations/OverviewOfSAR/remarkableStory.md
          - Range Resolution : foundations/OverviewOfSAR/rangeResolution.md
          - The Beautiful Equations : foundations/OverviewOfSAR/beautifulEquations.md
          - SAR Processing Overview : foundations/OverviewOfSAR/sarProcessing.md
          - Separating Signals From Noise : foundations/OverviewOfSAR/noise.md
          - The Innovation : foundations/OverviewOfSAR/theInnovation.md
          - Terminology : glossary.md
      - Geospatial Considerations : foundations/geospatialAccuracy.md
      - Radiometric Considerations : foundations/radiometric.md 
      - Slant to Ground Conversion : foundations/slantToGround.md
      - Validation : foundations/validation/geospatialValidation.md
    - ICEYE Archives : archive/archive.md
    - ICEYE Open Data : opendata/opendata.md
    - Change Log: changes.md
#    - About: about.md
theme:
    name: material
    palette:
    - scheme: iceye
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    primary: blue
    accent: green
    logo: assets/svg-iceye-logo-white.svg
    favicon: assets/favicon.ico
    custom_dir: overrides
    font: 
        text: Instrument Sans
        code: Space Mono
    features:
      - navigation.tracking

plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
   
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/iceyefi
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/ICEYEcom
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iceye
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/iceye
    - icon: svg-iceye-logo-white
      link: http://iceye.com
  analytics:
    provider: google
    property: G-G92GBM9X22
  homepage: https://www.iceye.com/


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 3
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
    - javascripts/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2025 - ICEYE
