site_name: ICEYE Product Documentation
site_description: Documentation related to ICEYE Products

# Repository
repo_name: ""
repo_url: ""
edit_uri: ""
site_url: https://www.iceye.com/

nav:
    - Welcome: index.md
    - The ICEYE Fleet: productguide/fleet.md
    - ICEYE Products: 
        - Product Types : productguide/products.md
        - Collection Characteristics : productguide/collectioncharacteristics.md
    - Ordering SAR imagery :
        - Ordering data: productguide/ordering.md
        - Support: productguide/support.md
    - Data Format Specification : 
        - SAR Data Formatting Options : productFormats/introduction.md
        - Packaging : productFormats/packaging.md
        - Foundations : 
            - Geospatial Considerations : productFormats/geospatialAccuracy.md
            - Radiometric Considerations : productFormats/radiometric.md 
            - Slant to Ground Conversion : productFormats/slantToGround.md
        - Image Products :
            - Single Look Complex Image : productFormats/slc.md
            - Amplitude Image : productFormats/grd.md
        - Metadata : productFormats/metadata.md
        # - from the product guide :  productguide/dataformats.md
    - What is SAR ? : 
        - The Value Of SAR Imaging : OverviewOfSAR/overviewOfSAR.md
        - A Simple Form Of RADAR Imaging : OverviewOfSAR/simpleFormOfImaging.md
        - The Remarkable Story Of SAR : OverviewOfSAR/remarkableStory.md
        - Range Resolution : OverviewOfSAR/rangeResolution.md
        - The Beautiful Equations : OverviewOfSAR/beautifulEquations.md
        - SAR Processing Overview : OverviewOfSAR/sarProcessing.md
        - Separating Signals From Noise : OverviewOfSAR/noise.md
        - The Innovation : OverviewOfSAR/theInnovation.md
        - Terminology : glossary.md
    # - Exploiting SAR Products :
    #     - The Basics : 
    #     - Advanced Tips and Tricks :
    #     - Snippets for Code Ninjas :
    - Coming Soon : comingsoon.md
    - About: about.md
theme:
    name: material
    palette:
    - scheme: iceye
      toggle:
        icon: material/theme-light-dark
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/theme-light-dark
        name: Switch to light mode
    primary: blue
    accent: green
    logo: assets/svg-iceye-logo-white.svg
    favicon: assets/favicon.ico
    custom_dir: overrides
    font: 
        text: Neuton
    features:
      - navigation.tracking

plugins:
  - search
  - bibtex:
      bib_file: "refs.bib"
      cite_style: "pandoc"
  - mike:
      # these fields are all optional; the defaults are as below...
      version_selector: true   # set to false to leave out the version selector
      css_dir: css             # the directory to put the version selector's CSS
      javascript_dir: js       # the directory to put the version selector's JS
      canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`
   
extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/iceyefi
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/ICEYEcom
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/iceye
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/iceye
    - icon: svg-iceye-logo-white
      link: http://iceye.com
  analytics:
    provider: google
    property: G-G92GBM9X22


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
        generic: true
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

copyright: Copyright &copy; 2022 - ICEYE